version: '3.8'
services:
  app:
    build: 
      context: .devcontainer
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/OctoPrint-Additv
      - ./.devcontainer/.octoprint:/home/vscode/.octoprint
    ports:
      - "5000:5000"
      - "5678:5678"
    command: sleep infinity
